// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture;

public interface CancelationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.CancelationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mycancelationresponse = 1;</code>
   */
  java.lang.String getMycancelationresponse();
  /**
   * <code>string mycancelationresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMycancelationresponseBytes();
}
