// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture;

public interface CancelationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.CancelationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
