// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture;

public interface CurrentStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.CurrentStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mycurrentstatusResponse = 1;</code>
   */
  java.lang.String getMycurrentstatusResponse();
  /**
   * <code>string mycurrentstatusResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMycurrentstatusResponseBytes();
}
