// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture;

public interface HumidityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.HumidityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myHumidityResponse = 1;</code>
   */
  java.lang.String getMyHumidityResponse();
  /**
   * <code>string myHumidityResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyHumidityResponseBytes();
}
