// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture;

public interface RainfallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.RainfallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myrainfall = 1;</code>
   */
  java.lang.String getMyrainfall();
  /**
   * <code>string myrainfall = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyrainfallBytes();
}
