// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture;

public interface RainfallResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.RainfallResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myRainfallResponse = 1;</code>
   */
  java.lang.String getMyRainfallResponse();
  /**
   * <code>string myRainfallResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyRainfallResponseBytes();
}
