// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mytemperatureresponse = 1;</code>
   */
  java.lang.String getMytemperatureresponse();
  /**
   * <code>string mytemperatureresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMytemperatureresponseBytes();
}
