// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mytemperature = 1;</code>
   */
  java.lang.String getMytemperature();
  /**
   * <code>string mytemperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getMytemperatureBytes();
}
