// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture1;

public final class ClimateService {
  private ClimateService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_TemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_HumidityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_HumidityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_HumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_HumidityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_RainfallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_RainfallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_RainfallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_RainfallResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service1.proto\022\020smartAgriculture\"+\n\022Te" +
      "mperatureRequest\022\025\n\rmytemperature\030\001 \001(\t\"" +
      "4\n\023TemperatureResponse\022\035\n\025mytemperaturer" +
      "esponse\030\001 \001(\t\"%\n\017HumidityRequest\022\022\n\nmyhu" +
      "midity\030\001 \001(\t\".\n\020HumidityResponse\022\032\n\022myhu" +
      "midityresponse\030\001 \001(\t\"9\n\017RainfallRequest\022" +
      "\023\n\013mystartdate\030\001 \001(\t\022\021\n\tmyenddate\030\002 \001(\t\"" +
      ".\n\020RainfallResponse\022\032\n\022myrainfalrRespons" +
      "e\030\001 \001(\t2\235\002\n\016climateService\022_\n\016GetTempera" +
      "ture\022$.smartAgriculture.TemperatureReque" +
      "st\032%.smartAgriculture.TemperatureRespons" +
      "e\"\000\022V\n\013GetHumidity\022!.smartAgriculture.Hu" +
      "midityRequest\032\".smartAgriculture.Humidit" +
      "yResponse\"\000\022R\n\007GetRain\022!.smartAgricultur" +
      "e.RainfallRequest\032\".smartAgriculture.Rai" +
      "nfallResponse\"\000B(\n\024grpc.ca.agriculture1B" +
      "\016ClimateServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartAgriculture_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartAgriculture_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_TemperatureRequest_descriptor,
        new java.lang.String[] { "Mytemperature", });
    internal_static_smartAgriculture_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartAgriculture_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_TemperatureResponse_descriptor,
        new java.lang.String[] { "Mytemperatureresponse", });
    internal_static_smartAgriculture_HumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartAgriculture_HumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_HumidityRequest_descriptor,
        new java.lang.String[] { "Myhumidity", });
    internal_static_smartAgriculture_HumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartAgriculture_HumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_HumidityResponse_descriptor,
        new java.lang.String[] { "Myhumidityresponse", });
    internal_static_smartAgriculture_RainfallRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartAgriculture_RainfallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_RainfallRequest_descriptor,
        new java.lang.String[] { "Mystartdate", "Myenddate", });
    internal_static_smartAgriculture_RainfallResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smartAgriculture_RainfallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_RainfallResponse_descriptor,
        new java.lang.String[] { "MyrainfalrResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
