// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture1;

public interface HumidityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.HumidityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myhumidity = 1;</code>
   */
  java.lang.String getMyhumidity();
  /**
   * <code>string myhumidity = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyhumidityBytes();
}
