// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture1;

public interface HumidityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.HumidityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the response is a floating-point value that represents the current humidity level of the environment as a percentage
   * </pre>
   *
   * <code>string myhumidityresponse = 1;</code>
   */
  java.lang.String getMyhumidityresponse();
  /**
   * <pre>
   * the response is a floating-point value that represents the current humidity level of the environment as a percentage
   * </pre>
   *
   * <code>string myhumidityresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyhumidityresponseBytes();
}
