// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture1;

public interface RainfallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.RainfallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
   * </pre>
   *
   * <code>string mystartdate = 1;</code>
   */
  java.lang.String getMystartdate();
  /**
   * <pre>
   *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
   * </pre>
   *
   * <code>string mystartdate = 1;</code>
   */
  com.google.protobuf.ByteString
      getMystartdateBytes();

  /**
   * <code>string myenddate = 2;</code>
   */
  java.lang.String getMyenddate();
  /**
   * <code>string myenddate = 2;</code>
   */
  com.google.protobuf.ByteString
      getMyenddateBytes();
}
