// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture1;

/**
 * <pre>
 * Define the messages for GetRain method
 * </pre>
 *
 * Protobuf type {@code smartAgriculture.RainfallRequest}
 */
public  final class RainfallRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartAgriculture.RainfallRequest)
    RainfallRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RainfallRequest.newBuilder() to construct.
  private RainfallRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RainfallRequest() {
    mystartdate_ = "";
    myenddate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RainfallRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            mystartdate_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            myenddate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.ca.agriculture1.ClimateService.internal_static_smartAgriculture_RainfallRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.ca.agriculture1.ClimateService.internal_static_smartAgriculture_RainfallRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ca.agriculture1.RainfallRequest.class, grpc.ca.agriculture1.RainfallRequest.Builder.class);
  }

  public static final int MYSTARTDATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object mystartdate_;
  /**
   * <pre>
   *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
   * </pre>
   *
   * <code>string mystartdate = 1;</code>
   */
  public java.lang.String getMystartdate() {
    java.lang.Object ref = mystartdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mystartdate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
   * </pre>
   *
   * <code>string mystartdate = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMystartdateBytes() {
    java.lang.Object ref = mystartdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mystartdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MYENDDATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object myenddate_;
  /**
   * <code>string myenddate = 2;</code>
   */
  public java.lang.String getMyenddate() {
    java.lang.Object ref = myenddate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      myenddate_ = s;
      return s;
    }
  }
  /**
   * <code>string myenddate = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMyenddateBytes() {
    java.lang.Object ref = myenddate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      myenddate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMystartdateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mystartdate_);
    }
    if (!getMyenddateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, myenddate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMystartdateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mystartdate_);
    }
    if (!getMyenddateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, myenddate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ca.agriculture1.RainfallRequest)) {
      return super.equals(obj);
    }
    grpc.ca.agriculture1.RainfallRequest other = (grpc.ca.agriculture1.RainfallRequest) obj;

    boolean result = true;
    result = result && getMystartdate()
        .equals(other.getMystartdate());
    result = result && getMyenddate()
        .equals(other.getMyenddate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MYSTARTDATE_FIELD_NUMBER;
    hash = (53 * hash) + getMystartdate().hashCode();
    hash = (37 * hash) + MYENDDATE_FIELD_NUMBER;
    hash = (53 * hash) + getMyenddate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ca.agriculture1.RainfallRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ca.agriculture1.RainfallRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Define the messages for GetRain method
   * </pre>
   *
   * Protobuf type {@code smartAgriculture.RainfallRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartAgriculture.RainfallRequest)
      grpc.ca.agriculture1.RainfallRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ca.agriculture1.ClimateService.internal_static_smartAgriculture_RainfallRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ca.agriculture1.ClimateService.internal_static_smartAgriculture_RainfallRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ca.agriculture1.RainfallRequest.class, grpc.ca.agriculture1.RainfallRequest.Builder.class);
    }

    // Construct using grpc.ca.agriculture1.RainfallRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mystartdate_ = "";

      myenddate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.ca.agriculture1.ClimateService.internal_static_smartAgriculture_RainfallRequest_descriptor;
    }

    @java.lang.Override
    public grpc.ca.agriculture1.RainfallRequest getDefaultInstanceForType() {
      return grpc.ca.agriculture1.RainfallRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ca.agriculture1.RainfallRequest build() {
      grpc.ca.agriculture1.RainfallRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ca.agriculture1.RainfallRequest buildPartial() {
      grpc.ca.agriculture1.RainfallRequest result = new grpc.ca.agriculture1.RainfallRequest(this);
      result.mystartdate_ = mystartdate_;
      result.myenddate_ = myenddate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ca.agriculture1.RainfallRequest) {
        return mergeFrom((grpc.ca.agriculture1.RainfallRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ca.agriculture1.RainfallRequest other) {
      if (other == grpc.ca.agriculture1.RainfallRequest.getDefaultInstance()) return this;
      if (!other.getMystartdate().isEmpty()) {
        mystartdate_ = other.mystartdate_;
        onChanged();
      }
      if (!other.getMyenddate().isEmpty()) {
        myenddate_ = other.myenddate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.ca.agriculture1.RainfallRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.ca.agriculture1.RainfallRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object mystartdate_ = "";
    /**
     * <pre>
     *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
     * </pre>
     *
     * <code>string mystartdate = 1;</code>
     */
    public java.lang.String getMystartdate() {
      java.lang.Object ref = mystartdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mystartdate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
     * </pre>
     *
     * <code>string mystartdate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMystartdateBytes() {
      java.lang.Object ref = mystartdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mystartdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
     * </pre>
     *
     * <code>string mystartdate = 1;</code>
     */
    public Builder setMystartdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mystartdate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
     * </pre>
     *
     * <code>string mystartdate = 1;</code>
     */
    public Builder clearMystartdate() {
      
      mystartdate_ = getDefaultInstance().getMystartdate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The method requires the user to provide two parameters: the start date and end date of the period they want to query.
     * </pre>
     *
     * <code>string mystartdate = 1;</code>
     */
    public Builder setMystartdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mystartdate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object myenddate_ = "";
    /**
     * <code>string myenddate = 2;</code>
     */
    public java.lang.String getMyenddate() {
      java.lang.Object ref = myenddate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        myenddate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string myenddate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMyenddateBytes() {
      java.lang.Object ref = myenddate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        myenddate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string myenddate = 2;</code>
     */
    public Builder setMyenddate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      myenddate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string myenddate = 2;</code>
     */
    public Builder clearMyenddate() {
      
      myenddate_ = getDefaultInstance().getMyenddate();
      onChanged();
      return this;
    }
    /**
     * <code>string myenddate = 2;</code>
     */
    public Builder setMyenddateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      myenddate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartAgriculture.RainfallRequest)
  }

  // @@protoc_insertion_point(class_scope:smartAgriculture.RainfallRequest)
  private static final grpc.ca.agriculture1.RainfallRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ca.agriculture1.RainfallRequest();
  }

  public static grpc.ca.agriculture1.RainfallRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RainfallRequest>
      PARSER = new com.google.protobuf.AbstractParser<RainfallRequest>() {
    @java.lang.Override
    public RainfallRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RainfallRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RainfallRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RainfallRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ca.agriculture1.RainfallRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

