// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture1;

public interface RainfallResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.RainfallResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The response to this method is a floating-point value that represents the total rainfall over the specified time period
   * </pre>
   *
   * <code>string myrainfalrResponse = 1;</code>
   */
  java.lang.String getMyrainfalrResponse();
  /**
   * <pre>
   * The response to this method is a floating-point value that represents the total rainfall over the specified time period
   * </pre>
   *
   * <code>string myrainfalrResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyrainfalrResponseBytes();
}
