// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.ca.agriculture1;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The response is a string with floating-point value that represents the current temperature of the environment
   * </pre>
   *
   * <code>string mytemperatureresponse = 1;</code>
   */
  java.lang.String getMytemperatureresponse();
  /**
   * <pre>
   * The response is a string with floating-point value that represents the current temperature of the environment
   * </pre>
   *
   * <code>string mytemperatureresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMytemperatureresponseBytes();
}
