// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture2;

public interface CancelationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.CancelationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mycancelationrequest = 1;</code>
   */
  java.lang.String getMycancelationrequest();
  /**
   * <code>string mycancelationrequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getMycancelationrequestBytes();
}
