// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture2;

public interface IrrigationParametersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.IrrigationParametersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myirrigationparameters = 1;</code>
   */
  java.lang.String getMyirrigationparameters();
  /**
   * <code>string myirrigationparameters = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyirrigationparametersBytes();
}
