// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture2;

public final class IrrigationService {
  private IrrigationService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_IrrigationParametersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_IrrigationParametersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_IrrigationStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_IrrigationStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_LocationParametersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_LocationParametersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_CurrentStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_CurrentStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_CancelationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_CancelationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_CancelationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_CancelationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service2.proto\022\020smartAgriculture\"=\n\033Ir" +
      "rigationParametersRequest\022\036\n\026myirrigatio" +
      "nparameters\030\001 \001(\t\">\n\030IrrigationStatusRes" +
      "ponse\022\"\n\032myirrigationstatusResponse\030\001 \001(" +
      "\t\"@\n\031LocationParametersRequest\022\020\n\010latitu" +
      "de\030\001 \001(\002\022\021\n\tlongitude\030\002 \001(\002\"8\n\025CurrentSt" +
      "atusResponse\022\037\n\027mycurrentstatusResponse\030" +
      "\001 \001(\t\" \n\022CancelationRequest\022\n\n\002id\030\001 \001(\005\"" +
      "4\n\023CancelationResponse\022\035\n\025mycancelationr" +
      "esponse\030\001 \001(\t2\324\002\n\021irrigationService\022l\n\rS" +
      "etIrrigation\022-.smartAgriculture.Irrigati" +
      "onParametersRequest\032*.smartAgriculture.I" +
      "rrigationStatusResponse\"\000\022j\n\016GetIrrigSta" +
      "tus\022+.smartAgriculture.LocationParameter" +
      "sRequest\032\'.smartAgriculture.CurrentStatu" +
      "sResponse\"\0000\001\022e\n\020CancelIrrigation\022$.smar" +
      "tAgriculture.CancelationRequest\032%.smartA" +
      "griculture.CancelationResponse\"\000(\0010\001B+\n\024" +
      "grpc.ca.agriculture2B\021IrrigationServiceP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartAgriculture_IrrigationParametersRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartAgriculture_IrrigationParametersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_IrrigationParametersRequest_descriptor,
        new java.lang.String[] { "Myirrigationparameters", });
    internal_static_smartAgriculture_IrrigationStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartAgriculture_IrrigationStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_IrrigationStatusResponse_descriptor,
        new java.lang.String[] { "MyirrigationstatusResponse", });
    internal_static_smartAgriculture_LocationParametersRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartAgriculture_LocationParametersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_LocationParametersRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_smartAgriculture_CurrentStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartAgriculture_CurrentStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_CurrentStatusResponse_descriptor,
        new java.lang.String[] { "MycurrentstatusResponse", });
    internal_static_smartAgriculture_CancelationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartAgriculture_CancelationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_CancelationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_smartAgriculture_CancelationResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smartAgriculture_CancelationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_CancelationResponse_descriptor,
        new java.lang.String[] { "Mycancelationresponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
