// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture2;

public interface IrrigationStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.IrrigationStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myirrigationstatusResponse = 1;</code>
   */
  java.lang.String getMyirrigationstatusResponse();
  /**
   * <code>string myirrigationstatusResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyirrigationstatusResponseBytes();
}
