// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package grpc.ca.agriculture2;

public interface LocationParametersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.LocationParametersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float latitude = 1;</code>
   */
  float getLatitude();

  /**
   * <code>float longitude = 2;</code>
   */
  float getLongitude();
}
