// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package grpc.ca.agriculture3;

public final class CropService {
  private CropService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_CropTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_CropTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_CropStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_CropStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_CropPlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_CropPlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartAgriculture_CropPlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartAgriculture_CropPlanResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service3.proto\022\020smartAgriculture\"%\n\017Cr" +
      "opTypeRequest\022\022\n\nmycroptype\030\001 \001(\t\"*\n\022Cro" +
      "pStatusResponse\022\024\n\014mycropstatus\030\001 \001(\t\"%\n" +
      "\017CropPlanRequest\022\022\n\nmycroptype\030\001 \001(\t\"$\n\020" +
      "CropPlanResponse\022\020\n\010cropPlan\030\001 \001(\t2\305\001\n\013c" +
      "ropService\022\\\n\rGetCropStatus\022!.smartAgric" +
      "ulture.CropTypeRequest\032$.smartAgricultur" +
      "e.CropStatusResponse\"\000(\001\022X\n\013GetCropPlan\022" +
      "!.smartAgriculture.CropPlanRequest\032\".sma" +
      "rtAgriculture.CropPlanResponse\"\0000\001B%\n\024gr" +
      "pc.ca.agriculture3B\013CropServiceP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartAgriculture_CropTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartAgriculture_CropTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_CropTypeRequest_descriptor,
        new java.lang.String[] { "Mycroptype", });
    internal_static_smartAgriculture_CropStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartAgriculture_CropStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_CropStatusResponse_descriptor,
        new java.lang.String[] { "Mycropstatus", });
    internal_static_smartAgriculture_CropPlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartAgriculture_CropPlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_CropPlanRequest_descriptor,
        new java.lang.String[] { "Mycroptype", });
    internal_static_smartAgriculture_CropPlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartAgriculture_CropPlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartAgriculture_CropPlanResponse_descriptor,
        new java.lang.String[] { "CropPlan", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
