// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package grpc.ca.agriculture3;

public interface CropTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.CropTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mycroptype = 1;</code>
   */
  java.lang.String getMycroptype();
  /**
   * <code>string mycroptype = 1;</code>
   */
  com.google.protobuf.ByteString
      getMycroptypeBytes();
}
