// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package grpc.ca.agriculture3;

public interface CropStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.CropStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mycropstatus = 1;</code>
   */
  java.lang.String getMycropstatus();
  /**
   * <code>string mycropstatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getMycropstatusBytes();
}
