// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package grpc.ca.agriculture3;

public interface CropPlanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartAgriculture.CropPlanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cropPlan = 1;</code>
   */
  java.lang.String getCropPlan();
  /**
   * <code>string cropPlan = 1;</code>
   */
  com.google.protobuf.ByteString
      getCropPlanBytes();
}
